### ISSUE TITLE
lexatrade.com

### ISSUE THREAD

**Issue by spirillen** [FiltersHeroes/KADhosts#77]
for what reason do you keep `lexatrade.com` in your blacklists. It looks pretty dead to me

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```yml
data/Ultimate.Hosts.Blacklist1.csv:lexatrade.com
data/kadhosts_azet12.csv:lexatrade.com
data/kadhosts_azet12.csv:www.lexatrade.com
```

#### Sorted result

```yml
www.lexatrade.com
```

### Search result from easylist

```yml
```

## Search in [Matrix](https://www.mypdns.org/)

```yml
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 1.56 KiB | 14.00 KiB/s, done.
From github.com:mypdns/matrix
   87757e8..36c6343  master     -> origin/master
```

Search results from [Matrix](https://www.mypdns.org) blacklist project

```yml
```

Did not find any matching RPZ records

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://www.mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Drilling for lexatrade.com

lexatrade.com.  172800  IN      NS      ns1.fp261.parklogic.com.
lexatrade.com.  172800  IN      NS      ns2.fp261.parklogic.com.
